pretrained_text_encoder_path: t2i_models/FLUX/FLUX.1-dev/text_encoder/model.safetensors
pretrained_text_encoder_2_path: t2i_models/FLUX/FLUX.1-dev/text_encoder_2
pretrained_dit_path: t2i_models/FLUX/FLUX.1-dev/flux1-dev.safetensors
pretrained_vae_path: t2i_models/FLUX/FLUX.1-dev/ae.safetensors
dataset_path: '/mnt/nas1/zhanghong/project/all2all/DiffSynth-Studio/data/all2all/embed/image_embeds_252.jsonl'
output_path: workdirs/visual2image/train
height: 512
width: 512
dataloader_num_workers: 12
learning_rate: 0.0001
lora_rank: 64
lora_alpha: 64
use_gradient_checkpointing: False
accumulate_grad_batches: 16
batch_size: 1
training_strategy: 'deepspeed_stage_3'
precision: 'bf16'
steps_per_epoch: 640000
max_epochs: 20
lr_warmup_steps: 500
wandb_api_key: 4bc3aa1826820be83c7e7ee086cf7256f7d40924
use_wandb: True
